// ─── MicroJSON Preset Schema ───────────────────────────────────────────────
// The central data contract of the Kinetia ecosystem.
// Every component (CV pipeline, animation engine, AE plugin) consumes this.

export type PresetCategory =
  | "entrance"
  | "exit"
  | "emphasis"
  | "transition"
  | "loop"
  | "text-reveal"
  | "kinetic-typography"
  | "logo-intro"
  | "particle"
  | "custom";

export type LayerType = "text" | "vector" | "image" | "shape" | "group";

export type AEProperty =
  | "position.x"
  | "position.y"
  | "scale.x"
  | "scale.y"
  | "scale.uniform"
  | "rotation"
  | "opacity"
  | "anchorPoint.x"
  | "anchorPoint.y"
  | "skew"
  | "skewAxis";

export type EasingType =
  | "linear"
  | "easeIn"
  | "easeOut"
  | "easeInOut"
  | "easeInQuad"
  | "easeOutQuad"
  | "easeInOutQuad"
  | "easeInCubic"
  | "easeOutCubic"
  | "easeInOutCubic"
  | "easeInBack"
  | "easeOutBack"
  | "easeInOutBack"
  | "easeInElastic"
  | "easeOutElastic"
  | "easeInOutElastic"
  | "easeInBounce"
  | "easeOutBounce"
  | "easeInOutBounce"
  | "custom";

export interface EasingDefinition {
  type: EasingType;
  /** Cubic bezier control points — required when type is "custom" */
  bezier?: [number, number, number, number];
}

export interface Keyframe {
  /** Time in milliseconds from animation start */
  time: number;
  /** Normalized value 0–1 (mapped to actual property range at apply time) */
  value: number;
  /** Easing for transition TO this keyframe */
  easing: EasingDefinition;
}

export interface PhysicsConfig {
  /** Spring tension 0–1 */
  tension: number;
  /** Damping / friction 0–1 */
  friction: number;
  /** Mass affects inertia 0.1–10 */
  mass: number;
  /** Bounce elasticity 0–1 */
  bounciness: number;
  /** Velocity decay factor 0–1 */
  velocityDecay: number;
  /** Random timing variation 0–1 (0 = deterministic) */
  randomness: number;
}

export interface AnimationTrack {
  /** Which AE property this track drives */
  property: AEProperty;
  keyframes: Keyframe[];
  /** Per-track physics override (merges with global PhysicsConfig) */
  physicsOverride?: Partial<PhysicsConfig>;
  /** Compiled AE expression string — generated by ae-expression-compiler */
  expression?: string;
}

export interface TargetConstraints {
  /** Layer types this preset is compatible with */
  layerTypes: LayerType[];
  /** Whether preset requires anchor point at center (50%, 50%) */
  requiresCenterAnchor: boolean;
  /** Minimum recommended layer dimensions in px */
  minDimensions?: { width: number; height: number };
}

export interface PresetMeta {
  name: string;
  description: string;
  category: PresetCategory;
  tags: string[];
  /** Duration in milliseconds */
  duration: number;
  /** FPS used during CV analysis */
  fps: number;
  /** Thumbnail image URL (S3/R2) */
  thumbnailUrl: string;
  createdAt: string;
  /** CV analysis confidence 0–1 */
  confidence: number;
}

export interface AnalysisMetadata {
  sourceVideoHash: string;
  opticalFlowMethod: string;
  trackedElements: number;
  processingTimeMs: number;
  frameCount: number;
}

export interface MicroJsonPreset {
  /** Schema version for forward compatibility */
  version: "1.0.0";
  id: string;
  meta: PresetMeta;
  targetConstraints: TargetConstraints;
  tracks: AnimationTrack[];
  physics: PhysicsConfig;
  /** Raw CV analysis data — present only on presets generated by pipeline */
  _analysis?: AnalysisMetadata;
}

export const DEFAULT_PHYSICS: PhysicsConfig = {
  tension: 0.5,
  friction: 0.6,
  mass: 1.0,
  bounciness: 0.0,
  velocityDecay: 0.8,
  randomness: 0.0,
};
