import type {
  MicroJsonPreset,
  AnimationTrack,
  PhysicsConfig,
  AEProperty,
} from "@kinetia/shared-types";
import { getEasingBezier, easingToAESnippet } from "./easing.js";
import { springExpression, bounceExpression } from "./physics.js";

/** Actual AE property ranges per normalized 0–1 value */
const PROPERTY_RANGES: Record<AEProperty, { min: number; max: number }> = {
  "position.x":     { min: -2000, max: 2000 },
  "position.y":     { min: -2000, max: 2000 },
  "scale.x":        { min: 0,     max: 200  },
  "scale.y":        { min: 0,     max: 200  },
  "scale.uniform":  { min: 0,     max: 200  },
  "rotation":       { min: -360,  max: 360  },
  "opacity":        { min: 0,     max: 100  },
  "anchorPoint.x":  { min: -1000, max: 1000 },
  "anchorPoint.y":  { min: -1000, max: 1000 },
  "skew":           { min: -90,   max: 90   },
  "skewAxis":       { min: -90,   max: 90   },
};

function normalizedToAE(value: number, property: AEProperty): number {
  const range = PROPERTY_RANGES[property];
  return range.min + value * (range.max - range.min);
}

function compileKeyframeExpression(track: AnimationTrack, physics: PhysicsConfig): string {
  const effectivePhysics = { ...physics, ...track.physicsOverride };
  const { keyframes, property } = track;

  if (keyframes.length === 1) {
    const kf = keyframes[0]!;
    const aeVal = normalizedToAE(kf.value, property);
    return `value; // Single keyframe: ${aeVal.toFixed(2)}`;
  }

  const kfLines = keyframes.map((kf, i) => {
    const aeVal = normalizedToAE(kf.value, property);
    const bezier = getEasingBezier(kf.easing);
    const easingSnippet = easingToAESnippet(bezier);
    return `  // KF[${i}] t=${kf.time}ms val=${aeVal.toFixed(2)} easing=${kf.easing.type}
  kfTimes[${i}] = ${(kf.time / 1000).toFixed(4)};
  kfValues[${i}] = ${aeVal.toFixed(4)};
  // ${easingSnippet}`;
  }).join("\n");

  const useBounce = effectivePhysics.bounciness > 0.1;
  const useSpring = effectivePhysics.tension > 0.1 && effectivePhysics.friction > 0;

  const lastKf = keyframes[keyframes.length - 1]!;
  const lastAeVal = normalizedToAE(lastKf.value, property);

  let physicsBlock = "";
  if (useSpring) {
    physicsBlock = springExpression(effectivePhysics, lastAeVal, property);
  } else if (useBounce) {
    physicsBlock = bounceExpression(effectivePhysics, property);
  }

  return `// Kinetia Expression — ${property}
// Generated by @kinetia/ae-expression-compiler v1.0.0
var startTime = inPoint;
var kfTimes = [];
var kfValues = [];
${kfLines}

var t = time - startTime;
var totalDur = kfTimes[kfTimes.length - 1];

if (t <= 0) {
  kfValues[0];
} else if (t >= totalDur) {
  ${physicsBlock ? `(function(){\n${physicsBlock}\n})()` : `kfValues[kfTimes.length - 1]`};
} else {
  var result = kfValues[0];
  for (var i = 0; i < kfTimes.length - 1; i++) {
    if (t >= kfTimes[i] && t < kfTimes[i+1]) {
      var segT = (t - kfTimes[i]) / (kfTimes[i+1] - kfTimes[i]);
      result = linear(segT, kfValues[i], kfValues[i+1]);
      break;
    }
  }
  result;
}`;
}

export interface CompileResult {
  property: AEProperty;
  expression: string;
}

/**
 * Compile all tracks in a MicroJsonPreset to AE expression strings.
 */
export function compileMicroJson(preset: MicroJsonPreset): CompileResult[] {
  return preset.tracks.map((track) => ({
    property: track.property,
    expression: compileKeyframeExpression(track, preset.physics),
  }));
}

/**
 * Compile a single track to an AE expression string.
 */
export function compileTrack(
  track: AnimationTrack,
  physics: PhysicsConfig
): string {
  return compileKeyframeExpression(track, physics);
}

/**
 * Inject compiled expressions back into preset tracks (mutates a copy).
 */
export function injectExpressions(preset: MicroJsonPreset): MicroJsonPreset {
  const compiled = compileMicroJson(preset);
  const expressionMap = new Map(compiled.map((r) => [r.property, r.expression]));

  return {
    ...preset,
    tracks: preset.tracks.map((track) => ({
      ...track,
      expression: expressionMap.get(track.property) ?? track.expression,
    })),
  };
}
